version: "3.9"
services:
  websocekt-service:
    image: romanowalex/websocekt-service:v1.0
    container_name: websocekt-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  websocekt-frontend:
    build: .
    image: romanowalex/websocekt-frontend:v1.0
    container_name: websocekt-frontend
    environment:
      BACKEND_HOST: websocekt-service
    ports:
      - "80:80"
    depends_on:
      - websocekt-service
