version: "3.9"
services:
  websocket-service:
    image: romanowalex/websocket-service:v1.0
    container_name: websocket-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  websocket-frontend:
    build: .
    image: romanowalex/websocket-frontend:v1.0
    container_name: websocket-frontend
    environment:
      BACKEND_HOST: websocket-service
    ports:
      - "80:80"
    depends_on:
      - websocket-service
