name: Build project
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: static
          path: build/
          retention-days: 1

  test:
    name: Test UI
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 3000,8080

      - name: Install test dependencies
        working-directory: ./test
        run: npm ci

      - name: Run tests
        working-directory: ./test
        run: node index.mjs --headless

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v

  publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: static
          path: build/

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: romanowalex/websocket-frontend:v2.0
          push: true